repos:
  - repo: local
    hooks:
      - id: black
        name: Code Prettifier - Black
        entry: python -m black "src/"
        language_version: python3.9
        language: python
        pass_filenames: false

      - id: flake8
        name: Code Linter - Flake8
        entry: python -m flake8 "src/"
        args: ['--config=linters/flake8.ini']
        language: python
        pass_filenames: false
  
      - id: isort
        name: Import Sorter - isort
        entry: python -m isort "src/"
        args: ['--settings-path=linters/isort.ini']
        language: python
        pass_filenames: false
