data_path: data/anglesey_84kph/datacollection
map_path: track_maps/monza_verysmooth.npy
particle_filter:
  n_particles: 500
  n_converged_particles: 500
  sampling_noise:
    x: 1.0
    y: 1.0
    yaw: 1.0 # deg
  control_noise:
    velocity: 0.1
    yaw:  1.0 # deg
  thresholds:
    offset: 10
    rotation: 90 # deg
    minimum_particles: 20
    track_limit: 1.0e6
  score_distribution:
    mean: 0
    sigma: 10
  convergence_criteria:
    maximum_distance: 30
    maximum_angle: 90 # deg
