experiment_name: "spa_audi"
data_path: localisation_data/spa_audi/slow
n_observations_between_plots: 10
vehicle:
    data_path: "data/audi_r8_lms_2016"
mapping:
  map_path: track_maps/spa_verysmooth.npy
localisation:
  n_particles: 500
  n_converged_particles: 500
  sampling_noise:
    x: 1.0
    y: 1.0
    yaw: 2.0 # deg
  control_noise:
    velocity: 2
    yaw:  0.16 # degrees
  thresholds:
    offset: 10
    rotation: 45 # deg
    minimum_particles: 20
    track_limit: 25
  score_distribution:
    mean: 0
    sigma: 10
  convergence_criteria:
    maximum_distance: 25
    maximum_angle: 60 # deg
  collect_benchmark_observations: False
  benchmark_observations_save_location: localisation_data
