experiment_name: 'silverstone_audi'
save_path: "data/testing"
evaluation: False
multithreading: True
test: False
seed: 0
vehicle:
    data_path: "data/audi_r8_lms_2016"
debugging:
    birds_eye_view_scale: 4
    birds_eye_view_size: 200
    verbose: True
is_streaming: False
data_collection:
    collect_images: 0
perception:
    model_segmentation: True
    model_path: "models/segmentation/silverstone-fpn-resnet-18-v1.1.pt"
    single_cam: True
    compile_model: False
    image_width: 1280
    image_height: 736
    n_polyfit_points: 500
    n_rows_to_remove_bonnet: 600
    centerline_from_track_limits: False
    vertical_fov_deg: 60
    position: [0.0, 1.45000, 0.56000]
    pitch_deg: 2.889419
mapping:
    map_path: track_maps/silverstone_verysmooth_2.npy
    create_map: False
    number_of_mapping_laps: 2
    control:
        horizon: 100
        speed_profile_constraints:
            v_min: 5.0
            v_max: 20.0
            a_min: -3.0
            a_max: 6.0
            ay_max: 2.0
            ki_min: 0.0
            end_velocity: 10.0
        step_cost: [1.0e-1, 1.0e-1, 0.0] # e_y, e_psi, t
        r_term: [1.0e-6, 1.0e+1] # velocity, steering
        final_cost: [0.0, 0.0, 1.0e-2] # e_y, e_psi, t
localisation:
    collect_benchmark_observations: False
    benchmark_observations_save_location: localisation_data
    use_localisation: False
    n_particles: 500
    n_converged_particles: 500
    sampling_noise:
        x: 1.1
        y: 1.1
        yaw: 3.0 # degrees
    control_noise:
        velocity: 0.25
        yaw:  2.0 # degrees
    thresholds:
        offset: 10
        rotation: 45 # deg
        minimum_particles: 20
        track_limit: 15.0
    score_distribution:
        mean: 0
        sigma: 10
    convergence_criteria:
        maximum_distance: 50
        maximum_angle: 90 # deg
racing:
    control:
        horizon: 100
        unlocalised_max_speed: 32
        speed_profile_constraints:
            v_min: 5.0
            v_max: 25.0
            a_min: -1.0
            a_max: 1.0
            ay_max: 3.0
            ki_min: 0.08
            end_velocity: 16.0
        step_cost: [1.0e-2, 5.0e-2, 0.0] # e_y, e_psi, t
        r_term: [1.0e-6, 10.0] # velocity, steering
        final_cost: [1.0, 0.0, 0.1] # e_y, e_psi, t
    map_speed_profile_constraints:
        ay_max: 6.5
        a_min: -0.15
acceleration_pid:
    throttle_pid:
        proportional: 0.05
        integral: 0.5
        derivative: -0.01
        sampling_interval_s: 0.01
    brake_pid:
        proportional: 0.26
        integral: 0.2
        derivative: 0.0
        sampling_interval_s: 0.01
steering_pid:
    proportional: 1.0
    integral: 0.0
    derivative: 0.0
    sampling_interval_s: 0.01
aci:
    race.ini:
        RACE:
            TRACK: "ks_silverstone"
            CONFIG_TRACK: "gp"
    video.ini:
        VIDEO:
            WIDTH: 1280
            HEIGHT: 736
    controls.ini:
        X360:
            SPEED_SENSITIVITY: 0.2
    assists.ini:
        ASSISTS:
            TYRE_BLANKETS: 1
    capture:
        images:
            image_format: "BGR0"
            wait_for_new_frames: False
        state:
            use_dicts: True