experiment_name: 'refactor-test'
save_path: "data/testing"
evaluation: True
multithreading: False
test: False
seed: 0
vehicle:
    wheel_base: 2.898
    width: 2.5
debugging:
    birds_eye_view_scale: 4
    birds_eye_view_size: 200
    show_camera: False
    show_control_image: True
    show_localisation_map: False
    show_segmentation: True
    show_visualised_predictions: False
    verbose: True
data_collection:
    collect_images: 0
perception:
    model_segmentation: True
    model_path: "agent/models/checkpoints/fpn-resnet-18-v3.ckpt"
    single_cam: True
    image_width: 1280
    image_height: 736
    centerline_from_tack_limits: False
    vertical_fov_deg: 60
    position: [0.0, 1.45000, 0.56000]
    pitch_deg: 2.889419
mapping:
    map_path: track_maps/monza
    create_map: True
    number_of_mapping_laps: 1
    control:
        horizon: 50
        speed_profile_constraints:
            v_min: 5.0
            v_max: 10.0
            a_min: -3.0
            a_max: 6.0
            ay_max: 4.0
        input_constraints:
            steering_max: 0.3
        wheel_base: 2.898
        step_cost: [1.0e-2, 0.0, 0.0] # e_y, e_psi, t
        r_term: [1.0e-6, 1.0e+1] # velocity, steering
        final_cost: [0.0, 0.0, 1.0e-4] # e_y, e_psi, t
localisation:
    use_localisation: False
    n_particles: 500
    n_converged_particles: 500
    sampling_noise:
        x: 1.0
        y: 1.0
        yaw: 1.0 # deg
    control_noise:
        velocity: 0.1
        yaw:  1.0 # deg
    thresholds:
        offset: 10
        rotation: 90 # deg
        minimum_particles: 20
        track_limit: 1.0e6
    score_distribution:
        mean: 0
        sigma: 10
    convergence_criteria:
        maximum_distance: 30
        maximum_angle: 90 # deg
racing:
    control:
        horizon: 50
        speed_profile_constraints:
            v_min: 5.0
            v_max: 60
            a_min: -0.12
            a_max: 6.0
            ay_max: 4.0
        input_constraints:
            steering_max: 0.3
        wheel_base: 2.898
        step_cost: [1.0e-2, 0.0, 0.0] # e_y, e_psi, t
        r_term: [1.0e-6, 1.0e+1] # velocity, steering
        final_cost: [0.0, 0.0, 1.0] # e_y, e_psi, t